"""Add work sessions

Revision ID: 506da97ac33d
Revises: a4b68d0a19fa
Create Date: 2026-08-20 16:17:20.987001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '506da97ac33d'
down_revision: Union[str, Sequence[str], None] = 'a4b68d0a19fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_task_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('planned_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('actual_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('session_state', sa.String(length=30), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=True),
    sa.Column('interrupted', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['daily_task_id'], ['daily_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_sessions')
    # ### end Alembic commands ###
