"""Add daily task state

Revision ID: a4b68d0a19fa
Revises: bfff2fa1bbf0
Create Date: 2026-08-20 10:40:00.754857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4b68d0a19fa'
down_revision: Union[str, Sequence[str], None] = 'bfff2fa1bbf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "daily_tasks",
        sa.Column(
            "state",
            sa.String(length=30),
            nullable=False,
            server_default="planned",
        ),
    )

    op.alter_column(
        "daily_tasks",
        "state",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_tasks', 'state')
    # ### end Alembic commands ###
